USE MAVENMOVIES;
SHOW TABLES;
SELECT* FROM RENTAL;
-- Use Mavenmovies database
-- 1. Display the first 10 records from the customer table.
SELECT* FROM CUSTOMER LIMIT 10;

-- 2. Display the first 3 records from the customer table whose first name starts with ‘b’.
SELECT* FROM CUSTOMER WHERE FIRST_NAME LIKE "B%" LIMIT 3;

-- 3. Display the names of the first 5 movies which are rated as ‘G’.
SELECT* FROM FILM WHERE RATING="G" LIMIT 5;

-- 4. Find all customers whose first name starts with "a".
SELECT* FROM CUSTOMER WHERE FIRST_NAME LIKE "A%";

-- 5. Find all customers whose first name ends with "a".
SELECT* FROM CUSTOMER WHERE FIRST_NAME LIKE "%A";

-- 6. Display the list of the first 4 cities which start and end with ‘a’.
SELECT* FROM CITY WHERE CITY LIKE "A%A" LIMIT 4;

-- 7. Find all customers whose first name has "NI" in any position.
SELECT* FROM CUSTOMER WHERE FIRST_NAME LIKE "%NI%";

-- 8. Find all customers whose first name has "r" in the second position.
SELECT* FROM CUSTOMER WHERE FIRST_NAME LIKE "_R%";

-- 9. Find all customers whose first name starts with "a" and is at least 5 characters in length.
SELECT* FROM CUSTOMER WHERE FIRST_NAME LIKE "A____%";

-- 10. Find all customers whose first name starts with "a" and ends with "o".
SELECT* FROM CUSTOMER WHERE FIRST_NAME LIKE "A%O";

-- 11. List all details of actors.
SELECT* FROM ACTOR;

-- 12. List all customer information from the database.
SELECT* FROM CUSTOMER;

-- 13. List different countries.
SELECT DISTINCT COUNTRY FROM COUNTRY;

-- 14. Display all active customers.
SELECT* FROM CUSTOMER WHERE ACTIVE =1;

-- 15. List all rental IDs for the customer with ID 1.
SELECT RENTAL_ID FROM RENTAL WHERE CUSTOMER_ID=1;

-- 16. Display all the films whose rental duration is greater than 5.
SELECT* FROM FILM WHERE RENTAL_DURATION > 5;

-- 17. List the total number of films whose replacement cost is greater than $15 and less than $20.
SELECT COUNT(*) FROM FILM WHERE REPLACEMENT_COST >15 AND REPLACEMENT_COST <20;

-- 18. Find the number of films whose rental rate is less than $1.
SELECT COUNT(*) FROM FILM WHERE RENTAL_RATE <1;

-- 19. List the total number of rentals for each customer, ordered by the total number of rentals in descending order.
SELECT CUSTOMER_ID, COUNT(RENTAL_ID) FROM RENTAL GROUP BY CUSTOMER_ID ORDER BY COUNT(RENTAL_ID) DESC;

-- 20. Find the average rental duration for each film rating, but only include categories where the average duration is more than 5 days.
SELECT DISTINCT RATING, AVG(RENTAL_DURATION) FROM FILM GROUP BY RATING HAVING AVG(RENTAL_DURATION)>5;

-- 21. Retrieve the top 10 customers who have made the highest total payments.
SELECT CUSTOMER_ID, SUM(AMOUNT) FROM PAYMENT GROUP BY CUSTOMER_ID ORDER BY SUM(AMOUNT) DESC LIMIT 10;

-- 22. List the films that have a rental rate between $2.00 and $4.00, ordered by title alphabetically.
SELECT TITLE FROM FILM WHERE RENTAL_RATE BETWEEN 2.00 AND 4.00 ORDER BY TITLE;

-- 23. Find the total number of active customers, grouped by store.
SELECT STORE_ID, COUNT(CUSTOMER_ID) FROM CUSTOMER WHERE ACTIVE=1 GROUP BY STORE_ID;

-- 24. List the number of films with each rating, ordered by the rating alphabetically.
SELECT RATING, COUNT(TITLE) FROM FILM GROUP BY RATING ORDER BY RATING;

-- 25. Calculate the total revenue generated by each staff and only include staff with revenue over $50,000.
SELECT STAFF_ID, SUM(AMOUNT) FROM PAYMENT GROUP BY STAFF_ID HAVING SUM(AMOUNT) > 50000;

-- 26. Retrieve the films that are longer than 120 minutes and order them by length in descending order.
SELECT TITLE, LENGTH FROM FILM WHERE LENGTH > 120 ORDER BY LENGTH DESC;

-- 27. List the total number of films in each rating category where the rental duration is exactly 7 days.
SELECT RATING, COUNT(TITLE) FROM FILM WHERE RENTAL_DURATION=7 GROUP BY RATING;

-- 28. Find the total number of films with a replacement cost greater than $20, grouped by rating.
SELECT RATING, COUNT(TITLE) FROM FILM WHERE REPLACEMENT_COST > 20 GROUP BY RATING;

-- 29. List the average rental rate of films in each language, and order the results by the average rate in ascending order.
SELECT LANGUAGE_ID, AVG(RENTAL_RATE) FROM FILM GROUP BY LANGUAGE_ID ORDER BY AVG(RENTAL_RATE) ASC;

-- 30. Calculate the total number of rentals made in the year 2006 and group them by month.
SELECT* FROM RENTAL;
SELECT* FROM FILM;
SELECT MONTH(RENTAL_DATE) FROM RENTAL WHERE YEAR(RENTAL_DATE) = 2006 ;

-- 31. Find the number of films that have a special feature of 'Behind the Scenes' and are less than 100 minutes long.
SELECT COUNT(TITLE) FROM FILM WHERE SPECIAL_FEATURES LIKE '%Behind the Scenes%' AND LENGTH < 100;

-- 32. Retrieve the films where the length is not equal to 90 minutes, grouped by length, and ordered by the number of films in descending order.
select* from film;
describe film;
SELECT length, count(title) as NO_OF_FILMS FROM FILM WHERE LENGTH <> 90 GROUP BY LENGTH order by no_of_films DESC;

-- 33. List the number of customers who have a staff ID of 1 and have made more than 10 rentals.
SELECT* FROM CUSTOMER; # customer_id, store_id, address_id, 
select* from staff; # staff_id=1, address_id, store_id=1
select* from rental; #rental_id, inventory_id, customer_id, staff_id

select customer_id, count(rental_id) as no_of_rentals from rental where staff_id=1 
	group by customer_id having count(rental_id)>10 order by no_of_rentals DESC;

-- 34. Find the total payment amount for each day in 2007, but only include days where the total payment exceeds $100.
select* from payment; 

select date(payment_date), sum(amount) as total_payment from payment where year(payment_date)=2007 
	group by date(payment_date) having sum(amount) > 100 order by total_payment DESC;

-- 35. Retrieve the films with a replacement cost that is not divisible by 5.
select* from film; # film_id, language_id, original_language_id, replacement_cost
select film_id, title, round(replacement_cost) as rounded_repl_cost from film where round(replacement_cost)%5 != 0;

-- 36. List the number of customers who signed up on each date in 2006, ordered by the date in ascending order.
select* from customer;
SELECT 
    DATE(create_date) AS signup_date,
    COUNT(*) AS customer_count
FROM 
    customer
WHERE 
    YEAR(create_date) = 2006
GROUP BY 
    DATE(create_date)
ORDER BY 
    signup_date ASC;

-- 37. Calculate the total number of payments made in each quarter of 2007.
select* from payment;

select quarter(payment_date) as Quarter, count(*) as Total_no_of_payments from payment where year(payment_date)=2007 group by quarter(payment_date);

-- 38. Find the films where the rental rate is either $0.99, $2.99, or $4.99, and order them by rental rate in ascending order.
select* from film;
select film_id, title, rental_rate from film where rental_rate = 0.99 or rental_rate = 2.99 or rental_rate = 4.99 order by rental_rate asc;
