CREATE DATABASE HR;
USE HR;
CREATE TABLE EMPLOYEES(
	EMP_ID CHAR(9) NOT NULL,
    F_NAME VARCHAR(15) NOT NULL,
    L_NAME VARCHAR(15) NOT NULL,
    SSN CHAR(9),
    B_DATE DATE,
    SEX CHAR,
    ADDRESS VARCHAR(30),
    JOB_ID CHAR(9),
    SALARY DECIMAL(10,2),
    MANAGER_ID CHAR(9),
    DEP_ID CHAR(9) NOT NULL,
    PRIMARY KEY (EMP_ID));
    
CREATE TABLE JOB_HISTORY(
	EMP_ID CHAR(9) NOT NULL,
    START_DATE DATE,
    JOB_ID CHAR(9) NOT NULL,
    DEPT_ID CHAR(9),
    PRIMARY KEY (EMP_ID, JOB_ID));
    
CREATE TABLE JOBS(
	JOB_IDENT CHAR(9) NOT NULL,
    JOB_TITLE VARCHAR(30),
    MIN_SALARY DECIMAL(10,2),
    MAX_SALARY DECIMAL(10,2),
    PRIMARY KEY (JOB_IDENT));
    
CREATE TABLE DEPARTMENTS(
	DEPT_ID_DEP CHAR(9) NOT NULL,
    DEP_NAME VARCHAR(15),
    MANAGER_ID CHAR(9),
    LOC_ID CHAR(9),
    PRIMARY KEY (DEPT_ID_DEP));
    
CREATE TABLE LOCATIONS(
	LOCT_ID CHAR(9) NOT NULL,
    DEP_ID_LOC CHAR(9) NOT NULL,
    PRIMARY KEY (LOCT_ID, DEP_ID_LOC));
    
SHOW TABLES;
SELECT* FROM EMPLOYEES;
SELECT* FROM JOBS;
    
-- 1. RETRIEVE ALL EMPLOYEES WHOSE ADDRESS IS IN ELGIN, IL

SELECT* FROM EMPLOYEES WHERE ADDRESS = "ELGIN, IL";
-- LIKE (WILD CARD)
SELECT* FROM EMPLOYEES WHERE ADDRESS LIKE "%ELGIN,IL%";
SELECT* FROM EMPLOYEES WHERE ADDRESS NOT LIKE "%ELGIN,IL%";
SELECT* FROM EMPLOYEES WHERE F_NAME LIKE "A%";
SELECT* FROM EMPLOYEES WHERE F_NAME LIKE "_N%";

-- 2. RETRIEVE ALL EMPLOYEES IN DEPARTMENT 5 WHOSE SALARY IS BETWEEN 60000 AND 70000
SELECT* FROM EMPLOYEES WHERE DEP_ID=5 AND SALARY BETWEEN 60000 AND 70000;
SELECT* FROM EMPLOYEES WHERE DEP_ID=5 AND SALARY >= 60000 AND SALARY <=70000;

-- 3. RETRIEVE A LIST OF EMPLOYEES ORDERED BY DEPARTMENT ID
SELECT* FROM EMPLOYEES ORDER BY DEP_ID;
SELECT* FROM EMPLOYEES ORDER BY DEP_ID DESC;
SELECT* FROM EMPLOYEES ORDER BY DEP_ID LIMIT 3;
SELECT* FROM EMPLOYEES ORDER BY DEP_ID DESC, SALARY DESC;

-- 4. FOR EACH DEPARTMENT ID RETRIEVE THE NUMBER OF EMPLOYEES IN THE DEPARTMENT

SELECT DEP_ID, COUNT(DEP_ID) AS NO_OF_EMPLOYEES FROM EMPLOYEES GROUP BY DEP_ID;

-- AGGREGATE FUNCTION
-- SUM(), COUNT(), MIN(), MAX(), AVG()

-- 5.	For each department retrieve the number of employees in the department, and 
-- the average employee salary in the department..
SELECT* FROM EMPLOYEES;
SELECT DEP_ID, COUNT(DEP_ID) AS NO_OF_EMPLOYEES, ROUND(AVG(SALARY),2) AS DEPT_AVG_SALARY FROM EMPLOYEES GROUP BY DEP_ID;

-- 6.	For each department retrieve the number of employees in the department, 
-- and the average employee salary in the department and limit the result to departments with fewer than 4 employees.

SELECT 
    DEP_ID, 
    COUNT(DEP_ID) AS NO_OF_EMPLOYEES, 
    ROUND(AVG(SALARY), 2) AS DEPT_AVG_SALARY
FROM 
    EMPLOYEES
GROUP BY 
    DEP_ID
HAVING 
    COUNT(DEP_ID) < 4;

